services:
  # Robô (Web Service)
  - type: web
    name: datafootball-analyzer-backend
    env: node
    region: oregon 
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: datafootball-db
          property: connectionString
      - key: API_KEY
        sync: false

  # Banco de Dados (Postgres Database)
  - type: pdb 
    name: datafootball-db
    region: oregon
    plan: free
    databaseName: datafootball_db
    user: datafootball_user
